[tools]
bun = "1.2.19"
lefthook = "1.12.2"

[hooks]
postinstall = ["bun install", "lefthook install"]

[env]
_.path = "node_modules/.bin"
_.file = ".env"

[tasks.fmt]
run = "biome check --write --unsafe ."

[tasks.test]
run = "bun test"
